=== bcheevers123/id-rather-be-sailing/pipeline/schemas/provider.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["id","official_name","alt_names","address","city","region","country","postcode","lat","lng","website","email","telephone","not_open_to_public"],
  "additionalProperties": false,
  "properties": {
    "id": {"type": "string", "pattern": "^[a-z0-9-]+$"},
    "official_name": {"type": "string", "minLength": 1},
    "alt_names": {"type": "array", "items": {"type": "string"}},
    "address": {"type": ["string","null"]},
    "city": {"type": ["string","null"]},
    "region": {"type": ["string","null"]},
    "country": {"type": ["string","null"]},
    "postcode": {"type": ["string","null"]},
    "lat": {"type": ["number","null"]},
    "lng": {"type": ["number","null"]},
    "website": {"type": ["string","null"]},
    "email": {"type": ["string","null"]},
    "telephone": {"type": ["string","null"]},
    "not_open_to_public": {"type": "boolean"}
  }
}

=== bcheevers123/id-rather-be-sailing/public/data/providers.json
[
  {
    "id": "police-service-of-northern-ireland-psni",
    "official_name": "Police Service of Northern Ireland\n(PSNI)",
    "alt_names": [],
    "address": "Not open to public",
    "city": null,
    "region": "Multi-Site",
    "country": "GB",
    "postcode": null,
    "lat": 36.9729856,
    "lng": -121.9967113,
    "website": null,
    "email": null,
    "telephone": null,
    "not_open_to_public": true
  },
  {
    "id": "3t-training-services-ltd",
    "official_name": "3t Training Services Limited",
    "alt_names": [],
    "address": "The Quay North Esplanade Aberdeen Aberdeenshire AB11 5QD",
    "city": null,
    "region": "Aberdeenshire",
    "country": "GB",
    "postcode": null,
    "lat": 57.166667,
    "lng": -2.666667,
    "website": "https://www.3tglobal.com/training-services/",
    "email": null,
    "telephone": "01224 794900",
    "not_open_to_public": false
  },
  {
    "id": "relyon-nutec-aberdeen",
    "official_name": "RelyOn Nutec (Aberdeen)",
    "alt_names": [],
    "address": "Folnavon Close, Aberdeen Airport East Dyce, Aberdeen Aberdeenshire\nAB21 7EG",
    "city": null,
    "region": "Aberdeenshire",
    "country": "GB",
    "postcode": null,
    "lat": 57.166667,
    "lng": -2.666667,
    "website": "https://relyonnutec.com/en_gb",
    "email": "bookings@uk.relyonnutec.com",
    "telephone": "+44 01224 928283",
    "not_open_to_public": false
  },
  {
    "id": "you-and-sea-ltd",
    "official_name": "You and Sea Ltd.",
    "alt_names": [],
    "address": "Helensburgh Leisure Centre, , 9 W Clyde St Helensburgh Argyll & Bute\nG84 8SQ",
    "city": null,
    "region": "Argyll & Bute",
    "country": "GB",
    "postcode": null,
    "lat": 56.4603494,
    "lng": -5.8618419,
    "website": "https://youandsea.com/",
    "email": "office@youandsea.com",
    "telephone": "01436 640303",
    "not_open_to_public": false
  },
  {
    "id": "falmouth-training-solutions",
    "official_name": "Falmouth Training Solutions",
    "alt_names": [],
    "address": "Bridge House Tregoniggie Falmouth Cornwall TR11 4SN",
    "city": null,
    "region": "Cornwall",
    "country": "GB",
    "postcode": null,
    "lat": 50.4433489,
    "lng": -4.6246566,
    "website": "https://falmouthtrainingsolutions.co.uk/",
    "email": "info@falmouthtrainingsolutions.co.uk",
    "telephone": "+44 (0)1326 211311",
    "not_open_to_public": false
  },
  {
    "id": "seafood-cornwall-training-ltd",
    "official_name": "Seafood Cornwall Training Ltd",
    "alt_names": [],
    "address": "Jubilee Pool Battery Road Penzance Cornwall TR18 4FF",
    "city": null,
    "region": "Cornwall",
    "country": "GB",
    "postcode": null,
    "lat": 50.4433489,
    "lng": -4.6246566,
    "website": "http://www.seafoodcornwalltraining.co.uk/",
    "email": "info@seafoodcornwalltraining.co.uk",
    "telephone": "01736 364324",
    "not_open_to_public": false
  },
  {
    "id": "stcw-training-uk-ltd",
    "official_name": "STCW Training UK Ltd",
    "alt_names": [],
    "address": "Whitecleaves Quarry Plymouth Road Buckfastleigh Devon TQ11 0DQ",
    "city": null,
    "region": "Devon",
    "country": "GB",
    "postcode": null,
    "lat": 50.7241405,
    "lng": -3.6607788,
    "website": "https://stcw-training-uk.com/",
    "email": "info@stcw-training-uk.com",
    "telephone": "01803 853843",
    "not_open_to_public": false
  },
  {
    "id": "royal-national-lifeboat-institution-rnli",
    "official_name": "Royal National Lifeboat Institution\n(RNLI)",
    "alt_names": [],
    "address": "West Quay Rd, Poole, Dorset, Dorset BH15 1HZ",
    "city": null,
    "region": "Dorset",
    "country": "GB",
    "postcode": null,
    "lat": 50.7968369,
    "lng": -2.3447323,
    "website": "http://www.rnli.org/",
    "email": "commercial_training@rnli.org.uk",
    "telephone": "01202 336461",
    "not_open_to_public": false
  },
  {
    "id": "relyon-nutec-teesside",
    "official_name": "RelyOn Nutec (Teesside)",
    "alt_names": [],
    "address": "Haverton Hill Industrial Estate, Billingham, Cleveland, Durham TS23 1PZ",
    "city": null,
    "region": "Durham",
    "country": "GB",
    "postcode": null,
    "lat": 54.666667,
    "lng": -1.75,
    "website": "https://relyonnutec.com/en_gb",
    "email": "bookings@uk.relyonnutec.com",
    "telephone": "+44 01224 928283",
    "not_open_to_public": false
  },
  {
    "id": "seahaven-maritime-academy",
    "official_name": "Seahaven Maritime Academy",
    "alt_names": [],
    "address": "East Quay, Newhaven Port, Newhaven, East Sussex BN9 0BN",
    "city": null,
    "region": "East Sussex",
    "country": "GB",
    "postcode": null,
    "lat": 50.9404266,
    "lng": 0.3699978,
    "website": "http://seahavenmaritimeacademy.co.uk/",
    "email": "hello@sma-training.co.uk",
    "telephone": "01273 514050",
    "not_open_to_public": false
  },
  {
    "id": "chieftain-training",
    "official_name": "Chieftain Training",
    "alt_names": [],
    "address": "26 Compass Point, Ensign Way, Hamble, Hampshire SO31 4RA",
    "city": null,
    "region": "Hampshire",
    "country": "GB",
    "postcode": null,
    "lat": 51.0449814,
    "lng": -1.2433102,
    "website": "https://chieftain.training/",
    "email": "info@chieftain.training",
    "telephone": "Email: info@chieftain.training",
    "not_open_to_public": false
  },
  {
    "id": "hamble-school-of-yachting",
    "official_name": "Hamble School of Yachting",
    "alt_names": [],
    "address": "Mercury Yacht Harbour, Satchell Lane, Hamble, Hampshire SO31 4HQ",
    "city": null,
    "region": "Hampshire",
    "country": "GB",
    "postcode": null,
    "lat": 51.0449814,
    "lng": -1.2433102,
    "website": "https://www.hamble.co.uk/",
    "email": "tuition@hamble.co.uk",
    "telephone": "023 8045 2668",
    "not_open_to_public": false
  },
  {
    "id": "mws-phoenix-training-group",
    "official_name": "MWS Phoenix Training Group",
    "alt_names": [],
    "address": "Not open to public",
    "city": null,
    "region": "Hampshire",
    "country": "GB",
    "postcode": null,
    "lat": 51.0449814,
    "lng": -1.2433102,
    "website": null,
    "email": null,
    "telephone": null,
    "not_open_to_public": true
  },
  {
    "id": "warsash-maritime-school-solent-university-southampton",
    "official_name": "Warsash Maritime School (Solent\nUniversity Southampton)",
    "alt_names": [],
    "address": "Safety Training Centre, Newtown Road, Warsash, Southampton,\nHampshire SO31 9ZL",
    "city": null,
    "region": "Hampshire",
    "country": "GB",
    "postcode": null,
    "lat": 51.0449814,
    "lng": -1.2433102,
    "website": "https://maritime.solent.ac.uk/",
    "email": "warsash.admissions@solent.ac.uk",
    "telephone": "+44 (0) 23 8201 5004",
    "not_open_to_public": false
  },
  {
    "id": "lagan-marine-training-recruitment",
    "official_name": "Lagan Marine Training &\nRecruitment",
    "alt_names": [],
    "address": "Unit 7 Stockmans Way Belfast BT9 7ET",
    "city": null,
    "region": "Ireland",
    "country": "GB",
    "postcode": null,
    "lat": 52.0600343,
    "lng": -0.347478,
    "website": "https://www.laganmarine.co.uk/",
    "email": "contact@laganmarine.co.uk",
    "telephone": "028 9066 1500",
    "not_open_to_public": false
  },
  {
    "id": "united-kingdom-sailing-academy-uksa",
    "official_name": "United Kingdom Sailing Academy\n(UKSA)",
    "alt_names": [],
    "address": "UK Sailing Academy Arctic Rd West Cowes Isle of Wight PO31 7PQ,",
    "city": null,
    "region": "Isle of Wight",
    "country": "GB",
    "postcode": null,
    "lat": 50.6710482,
    "lng": -1.3327111,
    "website": "https://uksa.org/",
    "email": "enquiries@uksa.org",
    "telephone": "01983 294941",
    "not_open_to_public": false
  },
  {
    "id": "national-maritime-training-centre",
    "official_name": "National Maritime Training Centre",
    "alt_names": [],
    "address": "North Kent College Lower Higham Road, Gravesend Kent DA12 2JJ",
    "city": null,
    "region": "Kent",
    "country": "GB",
    "postcode": null,
    "lat": 51.2474823,
    "lng": 0.7105077,
    "website": "http://www.northkent.ac.uk/",
    "email": "nmtc@northkent.ac.uk",
    "telephone": "01322 629400",
    "not_open_to_public": false
  },
  {
    "id": "relyon-liverpool",
    "official_name": "Relyon (Liverpool)",
    "alt_names": [],
    "address": "Unit 3, Earlsfield Park Arley Drive Prescot Merseyside L34 4BF",
    "city": null,
    "region": "Merseyside",
    "country": "GB",
    "postcode": null,
    "lat": 53.4953602,
    "lng": -2.973938,
    "website": null,
    "email": "kris.mcdonald@relyon.com",
    "telephone": "0151 708 9785",
    "not_open_to_public": false
  },
  {
    "id": "petans-ltd",
    "official_name": "Petans Limited",
    "alt_names": [],
    "address": "Petans Training Centre,Imperial Way, Horsham St Faith, Norwich, Norfolk\nNR10 3GJ",
    "city": null,
    "region": "Norfolk",
    "country": "GB",
    "postcode": null,
    "lat": 52.666667,
    "lng": 1.0,
    "website": "http://www.petans.co.uk/",
    "email": "info@petans.co.uk",
    "telephone": "+44 01603 891255",
    "not_open_to_public": false
  },
  {
    "id": "orkney-college",
    "official_name": "Orkney College",
    "alt_names": [],
    "address": "Department of Maritime Studies Victoria Street Stromness Orkney KW16\n3BS",
    "city": null,
    "region": "Orkney",
    "country": "GB",
    "postcode": null,
    "lat": 58.9418231,
    "lng": -3.1296944,
    "website": "http://www.orkney.uhi.ac.uk/",
    "email": "Orkney.College@uhi.ac.uk",
    "telephone": "01856 569000",
    "not_open_to_public": false
  },
  {
    "id": "university-of-the-highlands-and-islands-shetland",
    "official_name": "University of the Highlands and\nIslands Shetland",
    "alt_names": [],
    "address": "UHI Shetland Scalloway Campus Port Arthur Scalloway Shetland Shetland\nZE1 0UN",
    "city": null,
    "region": "Shetland",
    "country": "GB",
    "postcode": null,
    "lat": 60.333333,
